Repository depromeet/dpm-core-server, pull requests merged in 2025-08, with the labels that each got.

#114 fix: 어드민이 core 접근 시 admin 도메인으로 리다이렉트 되는 문제 수정
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberLoginService.kt
  src/main/kotlin/com/server/dpmcore/member/member/presentation/MemberLoginController.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/handler/CustomAuthenticationSuccessHandler.kt
Labels: 🐞 Bug

#120 refactor : 정산 조회 API '정산 중' 이후 상태에서 참석자 수 추가
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/BillDetailResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/BillListDetailResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/mapper/BillMapper.kt
Labels: 🔨 Refactor

#126 refactor : bill detail 버그 수정
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/mapper/BillMapper.kt
Labels: 🐞 Bug

#132 refactor: 출석 조퇴 상태 추가 (#131)
  src/main/kotlin/com/server/dpmcore/attendance/domain/model/AttendanceStatus.kt
Labels: 🔨 Refactor

#136 refactor : 참여 멤버 조회 리팩토링(Authority 다중 처리, 팀 번호 추가)
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringController.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/application/GatheringMemberQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/inbound/query/GatheringMemberIsJoinQueryModel.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/outbound/GatheringMemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberRepository.kt
Labels: 🔨 Refactor

#137 feat : 정산 참여 멤버들 응답 제출 여부 조회 API 구현
  src/main/kotlin/com/server/dpmcore/bill/bill/application/BillQueryService.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/port/inbound/query/BillMemberIsInvitationSubmittedQueryModel.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillQueryApi.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillQueryController.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/BillMemberSubmittedListResponse.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/GatheringQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/application/GatheringMemberQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/outbound/GatheringMemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberRepository.kt
  src/main/resources/db/schema.sql
Labels: ✨ Feature

#144 hotfix: gathering_members schema 변경에 따른 필드명 수정 반영
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/model/Bill.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/model/Gathering.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/model/GatheringMember.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/entity/GatheringMemberEntity.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/presentation/mapper/GatheringMemberMapper.kt
Labels: 🐞 Bug, 🔨 Refactor

#146 refactor: 도메인 서비스 간 의존 관계 추상화 및 모델 패키지 구조 개선
  src/main/kotlin/com/server/dpmcore/cohort/application/CohortQueryService.kt
  src/main/kotlin/com/server/dpmcore/cohort/domain/port/inbound/CohortQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/cohort/domain/port/outbound/CohortPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/cohort/infrastructure/repository/CohortRepository.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberQueryService.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/model/query/MemberNameAuthorityQueryModel.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/inbound/MemberQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/inbound/command/.gitkeep
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/outbound/MemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/member/member/infrastructure/repository/MemberRepository.kt
  src/main/kotlin/com/server/dpmcore/member/memberCohort/application/MemberCohortService.kt
  src/main/kotlin/com/server/dpmcore/session/application/SessionQueryService.kt
Labels: 🔨 Refactor

#154 fix : 정산 상세 조회 joinMemberCount 버그 수정
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/BillDetailGatheringResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/BillDetailInviteAuthorityResponse.kt
  src/main/kotlin/com/server/dpmcore/gathering/exception/GatheringException.kt
  src/main/kotlin/com/server/dpmcore/gathering/exception/GatheringExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/model/Gathering.kt
Labels: 🐞 Bug
