Repository depromeet/dpm-core-server, pull requests merged in 2025-07, with the labels that each got.

#26 feat: Attendance 도메인 및 JPA 엔티티 설계/구현
  .editorconfig
  build.gradle.kts
  src/main/kotlin/com/server/dpmcore/attendance/domain/model/Attendance.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/model/AttendanceId.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/model/AttendanceStatus.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/inbound/command/AttendanceCreateCommand.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/inbound/query/.gitkeep
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/outbound/AttendancePersistencePort.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/entity/AttendanceEntity.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/AttendanceJpaRepository.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/AttendanceRepository.kt
  src/main/kotlin/com/server/dpmcore/session/domain/model/AttendancePolicy.kt
  src/main/kotlin/com/server/dpmcore/session/domain/model/Session.kt
  src/main/kotlin/com/server/dpmcore/session/domain/model/SessionAttachment.kt
  src/main/kotlin/com/server/dpmcore/session/infrastructure/entity/SessionEntity.kt
Labels: ✨ Feature

#29 feat: Session 조회 및 출석 API 구현
  build.gradle.kts
  src/main/kotlin/com/server/dpmcore/attendance/application/AttendanceCommandService.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/model/Attendance.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/outbound/AttendancePersistencePort.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/entity/AttendanceEntity.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/AttendanceRepository.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceApi.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/dto/request/AttendanceCreateRequest.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/dto/response/AttendanceResponse.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/mapper/AttendanceMapper.kt
  src/main/kotlin/com/server/dpmcore/common/jdsl/QueryFactoryExtensions.kt
  src/main/kotlin/com/server/dpmcore/session/application/SessionQueryService.kt
  src/main/kotlin/com/server/dpmcore/session/application/config/SessionAttendanceProperties.kt
  src/main/kotlin/com/server/dpmcore/session/domain/exception/CheckedAttendanceException.kt
  src/main/kotlin/com/server/dpmcore/session/domain/exception/InvalidAttendanceCodeException.kt
  src/main/kotlin/com/server/dpmcore/session/domain/exception/SessionExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/session/domain/exception/SessionNotFoundException.kt
  src/main/kotlin/com/server/dpmcore/session/domain/exception/TooEarlyAttendanceException.kt
  src/main/kotlin/com/server/dpmcore/session/domain/model/AttendancePolicy.kt
  src/main/kotlin/com/server/dpmcore/session/domain/model/Session.kt
  src/main/kotlin/com/server/dpmcore/session/domain/port/inbound/command/SessionCreateCommand.kt
  src/main/kotlin/com/server/dpmcore/session/domain/port/outbound/SessionPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/session/infrastructure/entity/EmbeddedAttendancePolicy.kt
  src/main/kotlin/com/server/dpmcore/session/infrastructure/entity/SessionEntity.kt
  src/main/kotlin/com/server/dpmcore/session/infrastructure/repository/SessionRepository.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/controller/SessionApi.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/controller/SessionController.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/dto/response/NextSessionResponse.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/dto/response/SessionDetailResponse.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/dto/response/SessionListDetailResponse.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/dto/response/SessionListResponse.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/mapper/SessionMapper.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/mapper/TimeMapper.kt
  src/main/resources/application-local.yml
Labels: ✨ Feature, 🔨 Refactor

#30 feat: Spring Security 기반 카카오 OAuth 연동
  build.gradle.kts
  src/main/kotlin/com/server/dpmcore/DpmCoreServerApplication.kt
  src/main/kotlin/com/server/dpmcore/authority/infrastructure/entity/AuthorityEntity.kt
  src/main/kotlin/com/server/dpmcore/cohort/infrastructure/entity/CohortEntity.kt
  src/main/kotlin/com/server/dpmcore/member/member/infrastructure/entity/MemberEntity.kt
  src/main/kotlin/com/server/dpmcore/member/memberAuthority/infrastructure/entity/MemberAuthorityEntity.kt
  src/main/kotlin/com/server/dpmcore/member/memberCohort/infrastructure/entity/MemberCohortEntity.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/domain/OAuthProvider.kt
  src/main/kotlin/com/server/dpmcore/member/memberTeam/infrastructure/entity/MemberTeamEntity.kt
  src/main/kotlin/com/server/dpmcore/security/.gitkeep
  src/main/kotlin/com/server/dpmcore/security/configuration/SecurityConfig.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/domain/CustomOAuth2User.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/dto/KakaoAuthAttributes.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/dto/LoginResult.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/dto/OAuthAttributes.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/exception/OAuthExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/handler/CustomAuthenticationFailureHandler.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/handler/CustomAuthenticationSuccessHandler.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/handler/CustomOAuth2UserService.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/repository/AuthorizationRequestCookieValueMapper.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/repository/HttpCookieOAuth2AuthorizationRequestRepository.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/token/JwtAuthenticationFilter.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/token/JwtTokenProvider.kt
  src/main/kotlin/com/server/dpmcore/security/presentation/RedirectController.kt
  src/main/kotlin/com/server/dpmcore/security/properties/SecurityProperties.kt
  src/main/kotlin/com/server/dpmcore/security/properties/TokenProperties.kt
  src/main/kotlin/com/server/dpmcore/team/infrastructure/entity/TeamEntity.kt
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/static/kakao_login_btn.png
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: ✨ Feature, 🔨 Refactor

#46 feat : 정산 추가 구현 및 API
  src/main/kotlin/com/server/dpmcore/bill/bill/application/BillCommandService.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/model/Bill.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/port/BillPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/port/BillRepository.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/infrastructure/entity/BillEntity.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/infrastructure/repository/.gitkeep
  src/main/kotlin/com/server/dpmcore/bill/bill/infrastructure/repository/BillJpaRepository.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/infrastructure/repository/BillRepository.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandApi.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandController.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/CreateBillRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/CreateGatheringMemberRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/CreateGatheringRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/CreateReceiptPhotoRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/CreateReceiptRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/CreateBillResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/CreateGatheringMemberResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/CreateGatheringResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/CreateInviteGroupResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/CreateReceiptResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/mapper/BillMapper.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/application/BillAccountQueryService.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/domain/model/AccountType.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/domain/model/BillAccount.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/domain/port/BillAccountPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/domain/port/BillAccountRepository.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/infrastructure/repository/.gitkeep
  src/main/kotlin/com/server/dpmcore/bill/billAccount/infrastructure/repository/BillAccountJpaRepository.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/infrastructure/repository/BillAccountRepository.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/presentation/mapper/BillAccountMapper.kt
  src/main/kotlin/com/server/dpmcore/bill/exception/BillException.kt
  src/main/kotlin/com/server/dpmcore/bill/exception/BillExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/common/exception/CustomResponse.kt
  src/main/kotlin/com/server/dpmcore/common/exception/GlobalExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/model/Gathering.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/GatheringPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/infrastructure/entity/GatheringEntity.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/infrastructure/repository/.gitkeep
  src/main/kotlin/com/server/dpmcore/gathering/gathering/infrastructure/repository/GatheringRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/mapper/GatheringMapper.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/application/GatheringMemberCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/model/GatheringMember.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/GatheringMemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/.gitkeep
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/presentation/mapper/GatheringMemberMapper.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/application/ReceiptCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/domain/model/Receipt.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/domain/port/ReceiptPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/infrastructure/entity/ReceiptEntity.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/infrastructure/repository/.gitkeep
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/infrastructure/repository/ReceiptRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/presentation/mapper/ReceiptMapper.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceiptPhoto/domain/model/ReceiptPhoto.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceiptPhoto/domain/port/ReceiptPhotoPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceiptPhoto/infrastructure/entity/ReceiptPhotoEntity.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceiptPhoto/presentation/mapper/ReceiptPhotoMapper.kt
Labels: ✨ Feature

#55 refactor: CustomResponse 성공 응답 세분화 및 상태코드 적용 Aspect 추가
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandController.kt
  src/main/kotlin/com/server/dpmcore/common/exception/CustomResponse.kt
  src/main/kotlin/com/server/dpmcore/common/exception/CustomResponseStatusAspect.kt
  src/main/kotlin/com/server/dpmcore/common/exception/GlobalExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/member/member/presentation/MemberController.kt
Labels: 🔨 Refactor

#66 Fix : Bill 순환 참조 문제 해결
  src/main/kotlin/com/server/dpmcore/bill/bill/application/BillCommandService.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/application/BillQueryService.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/application/mapper/BillGatheringMapper.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/model/Bill.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/model/BillStatus.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/port/BillPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/port/inbound/BillQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/domain/port/outbound/BillPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/infrastructure/entity/BillEntity.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/infrastructure/repository/BillRepository.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandApi.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandController.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/CreateBillRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/CreateReceiptRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/GatheringForBillCreateRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/GatheringMemberForBillCreateRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/ReceiptForBillCreateRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/ReceiptPhotoForBillCreateRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/BillPersistenceResponse.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/mapper/BillMapper.kt
  src/main/kotlin/com/server/dpmcore/bill/exception/BillException.kt
  src/main/kotlin/com/server/dpmcore/bill/exception/BillExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/model/Gathering.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/GatheringPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/GatheringCreateUseCase.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/command/GatheringCreateCommand.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/outbound/GatheringPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/infrastructure/entity/GatheringEntity.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/infrastructure/repository/GatheringRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/mapper/GatheringMapper.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/model/GatheringMember.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/entity/GatheringMemberEntity.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/presentation/mapper/GatheringMemberMapper.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/application/ReceiptCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/domain/model/Receipt.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/domain/port/ReceiptPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/infrastructure/repository/ReceiptRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/presentation/mapper/ReceiptMapper.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceiptPhoto/presentation/mapper/ReceiptPhotoMapper.kt
Labels: 🐞 Bug, 🔨 Refactor

#70 refactor: 나의 세션 출석 상세 조회 API 수정 구현
  src/main/kotlin/com/server/dpmcore/attendance/application/AttendanceQueryService.kt
  src/main/kotlin/com/server/dpmcore/attendance/application/query/model/MemberDetailAttendanceQueryModel.kt
  src/main/kotlin/com/server/dpmcore/attendance/application/query/model/MyDetailAttendanceQueryModel.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/inbound/query/GetMyAttendanceBySessionQuery.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/outbound/AttendancePersistencePort.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/AttendanceRepository.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/QueryConditionExtensions.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceApi.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/dto/response/DetailMemberAttendancesResponse.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/dto/response/MyDetailAttendanceBySessionResponse.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/mapper/AttendanceMapper.kt
Labels: 🔨 Refactor

#72 feat: 세션 생성 이벤트 발행 및 구독을 통한 출석부 생성 구현
  src/main/kotlin/com/server/dpmcore/attendance/application/AttendanceCommandService.kt
  src/main/kotlin/com/server/dpmcore/attendance/application/AttendanceQueryService.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/inbound/query/GetAttendancesBySessionWeekQuery.kt
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/outbound/AttendancePersistencePort.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/entity/AttendanceEntity.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/event/listener/SessionCreateEventListener.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/AttendanceRepository.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/QueryConditionExtensions.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceApi.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/server/dpmcore/cohort/application/config/CohortProperties.kt
  src/main/kotlin/com/server/dpmcore/common/exception/CustomResponseStatusAspect.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberService.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/exception/MemberExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/exception/CohortMembersNotFoundException.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/outbound/MemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/member/member/infrastructure/repository/MemberRepository.kt
  src/main/kotlin/com/server/dpmcore/session/application/SessionCommandService.kt
  src/main/kotlin/com/server/dpmcore/session/domain/event/SessionCreateEvent.kt
  src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor

#75 refactor: 사람별 출석 리스트 조회 API 쿼리 수정
  build.gradle.kts
  src/main/kotlin/com/server/dpmcore/attendance/domain/port/inbound/query/GetAttendancesBySessionWeekQuery.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/AttendanceRepository.kt
  src/main/kotlin/com/server/dpmcore/attendance/infrastructure/repository/QueryConditionExtensions.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceApi.kt
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/server/dpmcore/cohort/application/CohortQueryService.kt
  src/main/kotlin/com/server/dpmcore/cohort/domain/port/CohortPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/cohort/infrastructure/repository/CohortRepository.kt
  src/main/kotlin/com/server/dpmcore/session/application/SessionQueryService.kt
  src/main/kotlin/com/server/dpmcore/session/application/query/SessionWeekQueryModel.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/dto/response/SessionWeeksResponse.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/mapper/SessionMapper.kt
  src/main/resources/application.yml
Labels: 🔨 Refactor

#77 refactor: Member 회원 가입 시 OAuth 연관 관계 정보 저장하도록 수정
  src/main/kotlin/com/server/dpmcore/cohort/domain/exception/CohortExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberLoginService.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/exception/MemberExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/exception/MemberIdCanNotBeNullException.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/model/Member.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/outbound/MemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/member/member/infrastructure/entity/MemberEntity.kt
  src/main/kotlin/com/server/dpmcore/member/member/infrastructure/repository/MemberRepository.kt
  src/main/kotlin/com/server/dpmcore/member/memberAuthority/application/MemberAuthorityService.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/application/MemberOAuthService.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/domain/MemberOAuthId.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/domain/model/MemberOAuth.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/domain/model/MemberOAuthId.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/domain/model/OAuthProvider.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/domain/port/MemberOAuthPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/infrastructure/entity/MemberOAuthEntity.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/infrastructure/repository/MemberOAuthJpaRepository.kt
  src/main/kotlin/com/server/dpmcore/member/memberOAuth/infrastructure/repository/MemberOAuthRepository.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/dto/KakaoAuthAttributes.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/dto/OAuthAttributes.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/exception/OAuthExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/exception/UnsupportedOAuthProviderException.kt
Labels: 🐞 Bug, 🔨 Refactor

#84 feat: 정산서 조회 체크 및 회식 참여 관련 API 구현
  src/main/kotlin/com/server/dpmcore/bill/bill/application/BillCommandService.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandApi.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandController.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/mapper/BillMapper.kt
  src/main/kotlin/com/server/dpmcore/gathering/exception/GatheringException.kt
  src/main/kotlin/com/server/dpmcore/gathering/exception/GatheringExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/GatheringCommandUseCase.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/GatheringQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/outbound/GatheringPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/infrastructure/repository/GatheringRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringApi.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringController.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/request/UpdateGatheringJoinsRequest.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/application/GatheringMemberCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/application/GatheringMemberQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/model/GatheringMember.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/inbound/GatheringMemberQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/outbound/GatheringMemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberJpaRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberRepository.kt
Labels: ✨ Feature, 🔨 Refactor

#88 feat: 정산 중 회식 참여 멤버 조회 API 구현
  src/main/kotlin/com/server/dpmcore/attendance/application/AttendanceCommandService.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/application/BillQueryService.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandApi.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillQueryApi.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillQueryController.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/response/BillSummaryListByMemberResponse.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/GatheringQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/query/GatheringMemberReceiptQueryModel.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringApi.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringController.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/response/GatheringMemberJoinListResponse.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/application/GatheringMemberQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/inbound/query/GatheringMemberIsJoinQueryModel.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/outbound/GatheringMemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/application/GatheringReceiptQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/domain/port/GatheringReceiptPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringReceipt/infrastructure/repository/GatheringReceiptRepository.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberLoginService.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberServiceQuery.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/exception/MemberExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/exception/MemberIdRequiredException.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/exception/MemberNameAuthorityRequiredException.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/inbound/MemberQueryByAuthorityUseCase.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/inbound/MemberQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/inbound/query/MemberNameAuthorityQueryModel.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/outbound/MemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/member/member/infrastructure/repository/MemberRepository.kt
  src/main/kotlin/com/server/dpmcore/member/member/presentation/MemberController.kt
  src/main/resources/db/schema.sql
Labels: ✨ Feature, 🐞 Bug

#92 fix : dev swagger cors 추가
  src/main/kotlin/com/server/dpmcore/security/configuration/SecurityConfig.kt
Labels: 🐞 Bug

#96 fix: 멤버 로그인 관련 1차 이슈 수정
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberLoginService.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/model/Member.kt
  src/main/kotlin/com/server/dpmcore/member/member/domain/port/inbound/HandleMemberLoginUseCase.kt
  src/main/kotlin/com/server/dpmcore/member/member/infrastructure/entity/MemberEntity.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/dto/KakaoAuthAttributes.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/dto/OAuthAttributes.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/handler/CustomAuthenticationFailureHandler.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/handler/CustomAuthenticationSuccessHandler.kt
  src/main/kotlin/com/server/dpmcore/security/properties/SecurityProperties.kt
  src/main/resources/application.yml
Labels: 🐞 Bug, 🔨 Refactor

#100 feat: API 권한 기반 접근 제어 처리
  src/main/kotlin/com/server/dpmcore/attendance/presentation/AttendanceController.kt
  src/main/kotlin/com/server/dpmcore/authority/application/AuthorityQueryService.kt
  src/main/kotlin/com/server/dpmcore/authority/domain/port/AuthorityPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/authority/domain/port/inbound/AuthorityQueryUseCase.kt
  src/main/kotlin/com/server/dpmcore/authority/domain/port/outbound/AuthorityPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/authority/infrastructure/repository/AuthorityRepository.kt
  src/main/kotlin/com/server/dpmcore/authority/presentation/AuthorityApi.kt
  src/main/kotlin/com/server/dpmcore/authority/presentation/AuthorityController.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandController.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillQueryController.kt
  src/main/kotlin/com/server/dpmcore/bill/billAccount/presentation/controller/BillAccountQueryController.kt
  src/main/kotlin/com/server/dpmcore/common/exception/GlobalExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringApi.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringController.kt
  src/main/kotlin/com/server/dpmcore/member/member/presentation/MemberController.kt
  src/main/kotlin/com/server/dpmcore/refreshToken/presentation/ReissueController.kt
  src/main/kotlin/com/server/dpmcore/security/configuration/SecurityConfig.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/service/CustomOAuth2UserService.kt
  src/main/kotlin/com/server/dpmcore/security/oauth/token/JwtTokenProvider.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/controller/SessionCommandController.kt
  src/main/kotlin/com/server/dpmcore/session/presentation/controller/SessionQueryController.kt
Labels: ✨ Feature, 🔨 Refactor

#99 Feat : 정산 참여 응답 상태 업데이트 구현, 정산 참여 API 리팩토링
  src/main/kotlin/com/server/dpmcore/bill/bill/application/BillCommandService.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandApi.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/controller/BillCommandController.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/SubmitBillParticipationConfirmRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/dto/request/UpdateGatheringJoinsRequest.kt
  src/main/kotlin/com/server/dpmcore/bill/bill/presentation/mapper/BillMapper.kt
  src/main/kotlin/com/server/dpmcore/gathering/exception/GatheringException.kt
  src/main/kotlin/com/server/dpmcore/gathering/exception/GatheringExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/gathering/exception/GatheringMemberException.kt
  src/main/kotlin/com/server/dpmcore/gathering/exception/GatheringMemberExceptionCode.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/application/GatheringCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/GatheringCommandUseCase.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/domain/port/inbound/command/GatheringCreateCommand.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringApi.kt
  src/main/kotlin/com/server/dpmcore/gathering/gathering/presentation/controller/GatheringController.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/application/GatheringMemberCommandService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/application/GatheringMemberQueryService.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/model/GatheringMember.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/domain/port/outbound/GatheringMemberPersistencePort.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/entity/GatheringMemberEntity.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberJpaRepository.kt
  src/main/kotlin/com/server/dpmcore/gathering/gatheringMember/infrastructure/repository/GatheringMemberRepository.kt
Labels: ✨ Feature, 🔨 Refactor

#109 refactor: 내 정보 조회 API에 권한 관련 필드 추가
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberLoginService.kt
  src/main/kotlin/com/server/dpmcore/member/member/application/MemberQueryService.kt
  src/main/kotlin/com/server/dpmcore/member/member/presentation/response/MemberDetailsResponse.kt
Labels: 🔨 Refactor
